version: '3.3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./data/html:/var/www/html
            - ./logs/nginx:/var/log/nginx
        ports:
            - "8080:80"
        links:
            - wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        user: "1000:1000"
        volumes:
            - ./data/html:/var/www/html
        ports:
            - "80:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

    db:
        image: mysql:latest
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        links:
            - db:mysql
        ports:
            - "8081:80"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
