version: '3.3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./data/html:/var/www/html
            - ./logs/nginx:/var/log/nginx
        ports:
            - "8080:80"
        links:
            - wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - ./data/html:/var/www/html
        ports:
            - "80:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: my_db_user
            WORDPRESS_DB_PASSWORD: my_db_pass
            WORDPRESS_DB_NAME: my_db_name

    db:
        image: mysql:latest
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my_root_pass
            MYSQL_DATABASE: my_db_name
            MYSQL_USER: my_db_user
            MYSQL_PASSWORD: my_db_pass

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        links:
            - db:mysql
        ports:
            - "8081:80"
        environment:
            MYSQL_ROOT_PASSWORD: my_root_pass
