services:
    nginx:
        container_name: nginx
        image: nginx:latest
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./data/html:/var/www/html
            - ./logs/nginx:/var/log/nginx
        ports:
            - 8080:80
        depends_on:
            - wordpress
        networks:
            - frontend

    wordpress:
        container_name: wp
        build:
            context: ./wordpress
            dockerfile: dev.dockerfile
        image: wp-php8.2-fpm.dev
        depends_on:
            - db
        volumes:
            - ./data/html:/var/www/html
        ports:
            - 80:80
        restart: always
        user: "1000:1000"
        networks:
            - frontend
            - backend
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

    db:
        container_name: db
        image: mysql:latest
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: always
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

    phpmyadmin:
        container_name: pma
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        networks:
            - backend
        ports:
            - 8081:80
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
    frontend:
        driver: bridge
        name: wp-frontend
    backend:
        driver: bridge
        name: wp-backend